version: 2.1
jobs:
  prep:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Set Up Environment
          command: |
            git submodule update --init
            ci_scripts/ci_tool.sh --setup_npm

      - restore_cache:
          key: |
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-

      - run:
            name: Install Dependencies
            command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - persist_to_workspace:
          root: ./
          paths:
            - .
  build:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Build
          command: |
            ci_scripts/ci_tool.sh --run_release
            VERSION=$(cat .version)
            PUBLIC_URL=/zethus/${VERSION}
            npm run build
            rm -rf dist && mv build dist
      - persist_to_workspace:
          root: ./
          paths:
            - dist
            - .version
  deploy:
    docker:
      - image: google/cloud-sdk:alpine
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: install jq
          command: apk add --no-cache jq
      - run:
          name: Publish
          command: |
            ci_scripts/ci_tool.sh --frontend_app_publish

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - prep:
          context: 6rs-circle
      - build:
          context: 6rs-circle
          requires:
            - prep
      - deploy:
          context: 6rs-circle
          requires:
            - prep
            - build
